// URLs públicas do IGDB — cole no DataviewJS substituindo: const COVER_MAP = {};

const COVER_MAP = {
  "1000 Miglia: Great 1000 Miles Rally": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8i4h.jpg",
  "Aqua Jack": "https://images.igdb.com/igdb/image/upload/t_cover_big/co66k7.jpg",
  "Arabian Magic": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2kua.jpg",
  "Arabian Fight": "https://images.igdb.com/igdb/image/upload/t_cover_big/co65ds.jpg",
  "Air Duel": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7f1r.jpg",
  "Air Assault": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7f1q.jpg",
  "Ashura Blaster": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3d5o.jpg",
  "Armed Police Batrider": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6i5o.jpg",
  "Asuka Asuka": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8hdq.jpg",
  "Asylum": "https://images.igdb.com/igdb/image/upload/t_cover_big/co89mb.jpg",
  "Batsugun": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6l6d.jpg",
  "Battle Rangers": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6olq.jpg",
  "Biomechanical Toy": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3rm9.jpg",
  "Big Karnak": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6zv4.jpg",
  "Caliber 50": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1ujz.jpg",
  "Cisco Heat": "https://images.igdb.com/igdb/image/upload/t_cover_big/co87zp.jpg",
  "Cosmic Cop": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7dxu.jpg",
  "Crime City": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3yu9.jpg",
  "Dangerous Seed": "https://images.igdb.com/igdb/image/upload/t_cover_big/jnyjkb2rcs0neerswdao.jpg",
  "Dangun Feveron": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7hli.jpg",
  "Darius Gaiden - Silver Hawk": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2eyg.jpg",
  "DoDonPachi": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3c0h.jpg",
  "DonPachi": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7u7n.jpg",
  "Dogyuun": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7ynq.jpg",
  "Dragon Blaze": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2nx1.jpg",
  "Dragon Breed": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2msq.jpg",
  "Dragon Saber": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2p8z.jpg",
  "Dragon Spirit": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2g1j.jpg",
  "Demon Front": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6vd8.jpg",
  "Espgaluda": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2q2f.jpg",
  "Final Star Force": "https://images.igdb.com/igdb/image/upload/t_cover_big/nogooubgktkeideudazw.jpg",
  "Fire Barrel": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7f1q.jpg",
  "Golden Axe - The Revenge of Death Adder": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6f4m.jpg",
  "G-Stream G2020": "https://images.igdb.com/igdb/image/upload/t_cover_big/h2vpqeemhxadzplijvwi.jpg",
  "Gunbird": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2evg.jpg",
  "Gunbird 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2evg.jpg",
  "Gunlock": "https://images.igdb.com/igdb/image/upload/t_cover_big/coa37f.jpg",
  "GunNail": "https://images.igdb.com/igdb/image/upload/t_cover_big/coalch.jpg",
  "Guwange": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2eyf.jpg",
  "Growl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2eyd.jpg",
  "Gundhara": "https://images.igdb.com/igdb/image/upload/t_cover_big/co798o.jpg",
  "Gratia - Second Earth": "https://images.igdb.com/igdb/image/upload/t_cover_big/ix5l2dzi4szpbiiwjcjw.jpg",
  "Gaiapolis": "https://images.igdb.com/igdb/image/upload/t_cover_big/co965x.jpg",
  "Gang Busters": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5g8t.jpg",
  "Gouketsuji Ichizoku Matsuri Senzo Kuyou": "https://images.igdb.com/igdb/image/upload/t_cover_big/ukhv8fazbcgenklx9yr5.jpg",
  "Grind Stormer": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2p15.jpg",
  "Hangzo": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9p5k.jpg",
  "Heated Barrel": "https://images.igdb.com/igdb/image/upload/t_cover_big/g3vrx38ykt9zxuotqrm8.jpg",
  "Jackal": "https://images.igdb.com/igdb/image/upload/t_cover_big/coa6pj.jpg",
  "Jail Break": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9681.jpg",
  "Koutetsu Yousai Strahl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4icm.jpg",
  "Ketsui - Kizuna Jigoku Tachi": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob6sl.jpg",
  "Knights of Valour Sangoku Senki": "https://images.igdb.com/igdb/image/upload/t_cover_big/coalco.jpg",
  "Knuckle Bash": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8037.jpg",
  "Last Duel": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2s51.jpg",
  "Lethal Crash Race": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7kxs.jpg",
  "Legendary Wings": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4qvi.jpg",
  "Legend of Heroes": "https://images.igdb.com/igdb/image/upload/t_cover_big/co96bb.jpg",
  "Mad Shark": "https://images.igdb.com/igdb/image/upload/t_cover_big/coad26.jpg",
  "Martial Masters Xing Yi Quan": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9paq.jpg",
  "Metamoqester": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9gy2.jpg",
  "Mad Motor": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2kz0.jpg",
  "Master of Weapon": "https://images.igdb.com/igdb/image/upload/t_cover_big/ys11etgjzc6hqqqtiyd5.jpg",
  "Mazinger Z": "https://images.igdb.com/igdb/image/upload/t_cover_big/coalkq.jpg",
  "Metal Black": "https://images.igdb.com/igdb/image/upload/t_cover_big/xhjm4okgjf1wvgxerwe0.jpg",
  "Mission Craft": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7nis.jpg",
  "Michael Jackson's Moonwalker": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6mpq.jpg",
  "Mutation Nation": "https://images.igdb.com/igdb/image/upload/t_cover_big/co27y4.jpg",
  "Magic Sword": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2toj.jpg",
  "Nostradamus": "https://images.igdb.com/igdb/image/upload/t_cover_big/i0yyg4qyhd12um1nentr.jpg",
  "NebulasRay": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2oyl.jpg",
  "Night Slashers": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobgxl.jpg",
  "Orius": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7neo.jpg",
  "Osman": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2z2v.jpg",
  "Out Zone": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4son.jpg",
  "Oriental Legend 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/dy3l0kmh2jxfshypdidl.jpg",
  "Primal Rage": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3s62.jpg",
  "P-47 Aces": "https://images.igdb.com/igdb/image/upload/t_cover_big/co67he.jpg",
  "Power Instinct": "https://images.igdb.com/igdb/image/upload/t_cover_big/co53gj.jpg",
  "Power Instinct 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2pbp.jpg",
  "Rayforce": "https://images.igdb.com/igdb/image/upload/t_cover_big/coa37f.jpg",
  "R-Shark": "https://images.igdb.com/igdb/image/upload/t_cover_big/pieud4gudwh4bx5jnfkp.jpg",
  "Rabio Lepus": "https://images.igdb.com/igdb/image/upload/t_cover_big/lxnscmjyss1jwvjoarcz.jpg",
  "Raiden": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5z96.jpg",
  "Raiden DX": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2fn7.jpg",
  "Raiden II": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2fn2.jpg",
  "Rapid Hero": "https://images.igdb.com/igdb/image/upload/t_cover_big/co66oq.jpg",
  "Rezon": "https://images.igdb.com/igdb/image/upload/t_cover_big/jaqiczo7pqekihgyyrey.jpg",
  "Ryu Jin": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9r3f.jpg",
  "Red Earth": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2oyb.jpg",
  "Riot": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6eda.jpg",
  "S.S. Mission": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1pdh.jpg",
  "Saint Dragon": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8t1b.jpg",
  "Samurai Aces": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wbd.jpg",
  "Sand Scorpion": "https://images.igdb.com/igdb/image/upload/t_cover_big/f1xwr4nywujzjx4wkz9s.jpg",
  "Sengeki Striker": "https://images.igdb.com/igdb/image/upload/t_cover_big/zlyjnunsx3kjsvfrt1b3.jpg",
  "Sky Soldiers": "https://images.igdb.com/igdb/image/upload/t_cover_big/co31g3.jpg",
  "Sky Smasher": "https://images.igdb.com/igdb/image/upload/t_cover_big/mdufn0flyxhrinr9tsqh.jpg",
  "Storm Blade": "https://images.igdb.com/igdb/image/upload/t_cover_big/cauk8l6q2syactx02uki.jpg",
  "Strikers 1945 II": "https://images.igdb.com/igdb/image/upload/t_cover_big/co276b.jpg",
  "Strikers 1945 III": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2z0m.jpg",
  "Super-X": "https://images.igdb.com/igdb/image/upload/t_cover_big/co685r.jpg",
  "Syvalion": "https://images.igdb.com/igdb/image/upload/t_cover_big/gsj827mwy7a0euhfrfom.jpg",
  "Stone Ball": "https://images.igdb.com/igdb/image/upload/t_cover_big/coam31.jpg",
  "Trojan": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3xyq.jpg",
  "Trio The Punch: Never Forget Me": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1iuc.jpg",
  "Tecmo Knight": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9qb9.jpg",
  "The Main Event": "https://images.igdb.com/igdb/image/upload/t_cover_big/crag9krgh00tghzr2zwk.jpg",
  "The Combatribes": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9lex.jpg",
  "The Simpsons": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9cl7.jpg",
  "Turbo Force": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3uc3.jpg",
  "Twin Cobra II": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3rke.jpg",
  "Thunder Cross": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6866.jpg",
  "Thunder Cross II": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5mwj.jpg",
  "Thunder Dragon": "https://images.igdb.com/igdb/image/upload/t_cover_big/ftwc3cf74apwifo4t2cq.jpg",
  "Thunder Dragon 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/iufjunexlrkbtvjeocjy.jpg",
  "Twin Cobra": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3rkf.jpg",
  "Twin Eagle II - The Rescue Mission": "https://images.igdb.com/igdb/image/upload/t_cover_big/co996c.jpg",
  "Tough Turf": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8039.jpg",
  "The Destroyer From Jail": "https://images.igdb.com/igdb/image/upload/t_cover_big/coavjt.jpg",
  "Ufo Robo Dangar": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3j71.jpg",
  "V-Five": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2p15.jpg",
  "Varia Metal": "https://images.igdb.com/igdb/image/upload/t_cover_big/co54nj.jpg",
  "Vandyke": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6no3.jpg",
  "Victory Road": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6o0m.jpg",
  "Vasara": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4hxz.jpg",
  "Vasara 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4hy0.jpg",
  "Vampire Savior: The Lord of Vampire": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobasm.jpg",
  "Violent Storm": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3rkp.jpg",
  "Willow": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wa6.jpg",
  "Warrior Blade: Rastan Saga Episode III": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4pz6.jpg",
  "Wizard Fire": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3to3.jpg",
  "World Rally": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3rmb.jpg",
  "WWF WrestleFest": "https://images.igdb.com/igdb/image/upload/t_cover_big/qicnwazvdhobiz4lnep1.jpg",
  "X-Men": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2646.jpg",
  "Zing Zing Zip": "https://images.igdb.com/igdb/image/upload/t_cover_big/coa34n.jpg",
  "Psyvariar -Medium Unit-": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4kyt.jpg",
  "Sagaia": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8wjn.jpg",
  "Shikigami no Shiro": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8iyf.jpg",
  "Star Soldier - Vanishing Earth": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7ofh.jpg",
  "Thunder Force AC": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7s5q.jpg",
  "Aero Fighters Special": "https://images.igdb.com/igdb/image/upload/t_cover_big/coa1e0.jpg",
  "Air Attack": "https://images.igdb.com/igdb/image/upload/t_cover_big/vltwvzbuxd1cm7iieoxs.jpg",
  "Akai Katana": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2kqx.jpg",
  "Black Heart": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4mft.jpg",
  "Chopper I": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9e5x.jpg",
  "Crazy War": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7nos.jpg",
  "Scud Race": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2xik.jpg",
  "Side by Side 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2eyg.jpg",
  "Master's Fury": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9pce.jpg",
  "Aqua GT": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7yes.jpg",
  "Border Down": "https://images.igdb.com/igdb/image/upload/t_cover_big/co23kq.jpg",
  "Capcom vs. SNK": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9gwf.jpg",
  "Carrier": "https://images.igdb.com/igdb/image/upload/t_cover_big/co40ek.jpg",
  "Chicken Run": "https://images.igdb.com/igdb/image/upload/t_cover_big/co99ka.jpg",
  "Daytona USA": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5v40.jpg",
  "Demolition Racer - No Exit": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2fgl.jpg",
  "Donald Duck - Quack Attack": "https://images.igdb.com/igdb/image/upload/t_cover_big/co434q.jpg",
  "Dynamite Cop!": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4lkr.jpg",
  "Expendable": "https://images.igdb.com/igdb/image/upload/t_cover_big/co40gw.jpg",
  "Gunlord": "https://images.igdb.com/igdb/image/upload/t_cover_big/r4k1r7tuwyakl7jkydd4.jpg",
  "Guilty Gear X": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vu3.jpg",
  "Headhunter": "https://images.igdb.com/igdb/image/upload/t_cover_big/co87sb.jpg",
  "JoJo's Bizarre Adventure": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5xx1.jpg",
  "Looney Tunes - Space Race": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7xg0.jpg",
  "Marvel vs. Capcom - Clash of Super Heroes": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8r3z.jpg",
  "Marvel vs. Capcom 2 - New Age of Heroe": "https://images.igdb.com/igdb/image/upload/t_cover_big/co870e.jpg",
  "NEO XYX": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7j0e.jpg",
  "Shadow Man": "https://images.igdb.com/igdb/image/upload/t_cover_big/co25wt.jpg",
  "Soldier of Fortune": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5xso.jpg",
  "South Park Rally": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3b86.jpg",
  "Spawn - In the Demon's Hand": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5mvt.jpg",
  "Speed Devils": "https://images.igdb.com/igdb/image/upload/t_cover_big/co43as.jpg",
  "Street Fighter Alpha 3": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6akr.jpg",
  "Sturmwind": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4mkh.jpg",
  "Super Runabout": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7sxx.jpg",
  "The Last Blade 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co23d7.jpg",
  "Tokyo Xtreme Racer": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5a1y.jpg",
  "Tokyo Xtreme Racer 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co44y2.jpg",
  "Under Defeat": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2pog.jpg",
  "Vanishing Point": "https://images.igdb.com/igdb/image/upload/t_cover_big/co28f6.jpg",
  "Zero Gunner 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4vl4.jpg",
  "Zombie Revenge": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2mse.jpg",
  "Wacky Races Starring Dastardly Muttley": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5rwi.jpg",
  "Bonk's Adventure": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7k2v.jpg",
  "Atomic Punk": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6l2d.jpg",
  "BATTLETOADS DOUBLE DRAGON": "https://images.igdb.com/igdb/image/upload/t_cover_big/co70ds.jpg",
  "Disney's TaleSpin": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3lh0.jpg",
  "Gargoyles Quest": "https://images.igdb.com/igdb/image/upload/t_cover_big/co27rm.jpg",
  "Hammerin' Harry: Ghost Building Company": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9ht2.jpg",
  "Kid Dracula": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6vv9.jpg",
  "Looney Tunes": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7xtk.jpg",
  "Mighty Morphin Power Rangers": "https://images.igdb.com/igdb/image/upload/t_cover_big/co63o5.jpg",
  "Makaimura Gaiden: The Demon Darkness": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6ds7.jpg",
  "Operation C": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6fy1.jpg",
  "Speedy Gonzales": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2doo.jpg",
  "Taz-Mania": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2dow.jpg",
  "Trip World": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3xra.jpg",
  "Tiny Toon Adventures 2: Montana's Movie Madness": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2dph.jpg",
  "The Amazing Spider-Man": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2dp3.jpg",
  "Disney's Donald Duck: Goin' Quackers": "https://images.igdb.com/igdb/image/upload/t_cover_big/co31a1.jpg",
  "Disney's Atlantis: The Lost Empire": "https://images.igdb.com/igdb/image/upload/t_cover_big/co913n.jpg",
  "Survival Kids": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8hhx.jpg",
  "X-Men: Wolverine's Rage": "https://images.igdb.com/igdb/image/upload/t_cover_big/co980z.jpg",
  "Asterix Obelix - Bash Them All!": "https://images.igdb.com/igdb/image/upload/t_cover_big/co50nu.jpg",
  "Avatar: The Last Airbender": "https://images.igdb.com/igdb/image/upload/t_cover_big/co504n.jpg",
  "Droopys Tennis Open": "https://images.igdb.com/igdb/image/upload/t_cover_big/ybmatqa6lajw28x7hb6h.jpg",
  "Fire Pro Wrestling": "https://images.igdb.com/igdb/image/upload/t_cover_big/coatix.jpg",
  "Gekido Advance: Kintaro's Revenge": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2w76.jpg",
  "Jackie Chan Adventures: Legend of the Dark Hand": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4e84.jpg",
  "Kong - The 8th Wonder of the world": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9u5f.jpg",
  "Kong: The Animated Series": "https://images.igdb.com/igdb/image/upload/t_cover_big/co86c7.jpg",
  "Medal of Honor Infiltrator": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3nfh.jpg",
  "Pitfall": "https://images.igdb.com/igdb/image/upload/t_cover_big/co87vu.jpg",
  "Rage Against Road": "https://images.igdb.com/igdb/image/upload/t_cover_big/co50lq.jpg",
  "Breath of Fire 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8dq3.jpg",
  "Super Puzzle Fighter II Turbo": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8iz2.jpg",
  "Tak: The Great Juju Challenge": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5wse.jpg",
  "Teen Titans 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6iv6.jpg",
  "The Scorpion King": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2d6w.jpg",
  "Tom and Jerry: Infurnal Escape": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4i3v.jpg",
  "Shinobi II The Silent Fury": "https://images.igdb.com/igdb/image/upload/t_cover_big/co30it.jpg",
  "Land of Illusion Starring Mickey Mouse": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4zmt.jpg",
  "Legend of Illusion Starring Mickey Mouse": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6fbb.jpg",
  "Master of Darkness": "https://images.igdb.com/igdb/image/upload/t_cover_big/co88ka.jpg",
  "Sonic the Hedgehog 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1zus.jpg",
  "Tom and Jerry: The Movie": "https://images.igdb.com/igdb/image/upload/t_cover_big/co71e2.jpg",
  "The Lucky Dime Caper Starring Donald Duck": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7tyb.jpg",
  "Vampire: Master of Darkness": "https://images.igdb.com/igdb/image/upload/t_cover_big/co88ka.jpg",
  "Asterix and the Great Rescue": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4ebr.jpg",
  "Arcus Odyssey": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9v1t.jpg",
  "Alien 3": "https://images.igdb.com/igdb/image/upload/t_cover_big/co47dv.jpg",
  "Bubble and Squeak": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5k22.jpg",
  "Blades of Vengeance": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5k26.jpg",
  "Batman Returns": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3zck.jpg",
  "Batman - Revenge of the Joker": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5yv3.jpg",
  "Cosmic Spacehead": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3klf.jpg",
  "Contra Hard Corps": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2n11.jpg",
  "Castle of Illusion Starring Mickey Mouse": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1y83.jpg",
  "Coffee Crisis": "https://images.igdb.com/igdb/image/upload/t_cover_big/co23me.jpg",
  "Dr. Robotnik's Mean Bean Machine": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2v8c.jpg",
  "Demons of Asteborg": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2oc4.jpg",
  "Eternal Champions": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2er8.jpg",
  "Eliminate Down": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2er9.jpg",
  "El Viento": "https://images.igdb.com/igdb/image/upload/t_cover_big/co289o.jpg",
  "Generations Lost": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5lfq.jpg",
  "Goofy's Hysterical History Tour": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4zn3.jpg",
  "Global Gladiators": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4i6v.jpg",
  "Garfield: Caught in the Act": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3s86.jpg",
  "Kid Chameleon": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6q7b.jpg",
  "L'Abbaye des Morts": "https://images.igdb.com/igdb/image/upload/t_cover_big/co76pa.jpg",
  "Life on Mars: Genesis": "https://images.igdb.com/igdb/image/upload/t_cover_big/co71lt.jpg",
  "Mighty Morphin Power Rangers: The Movie": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2by0.jpg",
  "Metal Dragon": "https://images.igdb.com/igdb/image/upload/t_cover_big/co952r.jpg",
  "Outlander": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5ozi.jpg",
  "Red Zone": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5p3z.jpg",
  "Spider-Man": "https://images.igdb.com/igdb/image/upload/t_cover_big/co98ia.jpg",
  "Skeleton Krew": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8gjt.jpg",
  "Shadowrun": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4tp6.jpg",
  "Skitchin'": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5p8d.jpg",
  "Techno Cop": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2yv6.jpg",
  "Thunder Force IV": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4b27.jpg",
  "The Punisher": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2649.jpg",
  "Tanglewood": "https://images.igdb.com/igdb/image/upload/t_cover_big/co227k.jpg",
  "Tom and Jerry: Frantic Antics!": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2dpk.jpg",
  "The Lost Vikings": "https://images.igdb.com/igdb/image/upload/t_cover_big/co54sf.jpg",
  "Twinkle Tale": "https://images.igdb.com/igdb/image/upload/t_cover_big/co52wk.jpg",
  "The Curse of Illmoore Bay": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5mzz.jpg",
  "Two Crude Dudes": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wwk.jpg",
  "Ultracore": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2t7f.jpg",
  "Urban Strike: The Sequel to Jungle Strike": "https://images.igdb.com/igdb/image/upload/t_cover_big/co47q8.jpg",
  "Wolfchild": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2jjx.jpg",
  "Alpha Mission II ASO II - Last Guardian": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ku8.jpg",
  "Art of Fighting 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co22y5.jpg",
  "Art of Fighting 3": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1zh4.jpg",
  "Blazing Star": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1zh7.jpg",
  "Captain Tomaday": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4ss3.jpg",
  "Eight Man": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7yk5.jpg",
  "Far East of Eden - Kabuki Klash Tengai Makyou - Shin Den": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5xip.jpg",
  "Ganryu": "https://images.igdb.com/igdb/image/upload/t_cover_big/syjxojnda6h4lamw7abm.jpg",
  "Ghost Pilots": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9a5c.jpg",
  "Magician Lord": "https://images.igdb.com/igdb/image/upload/t_cover_big/co47z6.jpg",
  "Prehistoric Isle 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3g36.jpg",
  "Pulstar": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1w28.jpg",
  "Robo Army": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9dka.jpg",
  "Rage of the Dragons": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ek0.jpg",
  "Savage Reign": "https://images.igdb.com/igdb/image/upload/t_cover_big/co25k6.jpg",
  "Samurai Shodown II": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2r8h.jpg",
  "Shock Troopers": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ny0.jpg",
  "Shock Troopers - 2nd Squad": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ny0.jpg",
  "Sengoku 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/coaw8h.jpg",
  "Sengoku 3": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1w4y.jpg",
  "World Heroes 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2rwb.jpg",
  "World Heroes": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2rwb.jpg",
  "Al Unser Jr.'s Turbo Racing": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6ns1.jpg",
  "Bad Dudes": "https://images.igdb.com/igdb/image/upload/t_cover_big/co55jp.jpg",
  "Championship Rally": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3vrt.jpg",
  "Heavy Barrel": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2fd1.jpg",
  "Isolated Warrior": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6o0a.jpg",
  "Journey to Silius": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2oiz.jpg",
  "Jurassic Park": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2zpb.jpg",
  "Kick Master": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4pzo.jpg",
  "Rush'n Attack": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7s8y.jpg",
  "Sword Master": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6fgq.jpg",
  "Spider-Man: Return of the Sinister Six": "https://images.igdb.com/igdb/image/upload/t_cover_big/co987q.jpg",
  "The Legend of Prince Valiant": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6o2h.jpg",
  "The Adventures of Bayou Billy": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6v27.jpg",
  "Aliens: Infestation": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2dfr.jpg",
  "Batman: The Brave and The Bold - The Videogame": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9s86.jpg",
  "Bejeweled 3": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4zso.jpg",
  "Commando: Steel Disaster": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9rz4.jpg",
  "Contra 4": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2guv.jpg",
  "Grand Theft Auto: Chinatown Wars": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lba.jpg",
  "Kirby: Squeak Squad": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4385.jpg",
  "Kirby Super Star Ultra": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3g9j.jpg",
  "Monster Tale": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2o56.jpg",
  "Prince of Persia The Fallen King": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ouc.jpg",
  "Tetris DS": "https://images.igdb.com/igdb/image/upload/t_cover_big/co65xn.jpg",
  "The Legend of Zelda: Spirit Tracks": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3oj6.jpg",
  "Alundra": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3tlr.jpg",
  "Art Camion Geijutsu-den": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob8ym.jpg",
  "Alundra 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4py4.jpg",
  "Breath of Fire 3": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9jxg.jpg",
  "Bakusou Dekotora Densetsu": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8qcg.jpg",
  "Disney's Hercules": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5l0x.jpg",
  "Dino Crisis": "https://images.igdb.com/igdb/image/upload/t_cover_big/co530k.jpg",
  "Dino Crisis 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8qbu.jpg",
  "Formula One 99": "https://images.igdb.com/igdb/image/upload/t_cover_big/co78k7.jpg",
  "Herc's Adventures": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2qbz.jpg",
  "Harmful Park": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4l2x.jpg",
  "Jarrett Labonte Stock Car Racing": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8hhg.jpg",
  "Jackie Chan Stuntmaster": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2f8i.jpg",
  "Micro Maniacs Racing": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4m3l.jpg",
  "Mega Man X4": "https://images.igdb.com/igdb/image/upload/t_cover_big/coar91.jpg",
  "Parodius": "https://images.igdb.com/igdb/image/upload/t_cover_big/co40ch.jpg",
  "Pocket Fighter": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6dfb.jpg",
  "Oddworld: Abe's Oddysee": "https://images.igdb.com/igdb/image/upload/t_cover_big/co89fk.jpg",
  "Racing Lagoon": "https://images.igdb.com/igdb/image/upload/t_cover_big/co46x8.jpg",
  "Rival Schools: United by Fate": "https://images.igdb.com/igdb/image/upload/t_cover_big/co97h0.jpg",
  "Shiritsu Justice Gakuen: Nekketsu Seishun Nikki 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/cob0ox.jpg",
  "Soviet Strike": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1uc1.jpg",
  "Suikoden 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1y6a.jpg",
  "Strider 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9ifa.jpg",
  "Skullmonkeys": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1o53.jpg",
  "Sled Storm": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2eka.jpg",
  "Wild Arms": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1war.jpg",
  "Mickey Mania: The Timeless Adventures of Mickey Mouse": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6qh4.jpg",
  "Pitfall - The Mayan Adventure": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2fsd.jpg",
  "The Amazing Spider-Man vs. The Kingpin": "https://images.igdb.com/igdb/image/upload/t_cover_big/co85oo.jpg",
  "Ultraverse Prime": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9pfm.jpg",
  "Wonder Dog": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5b2l.jpg",
  "Asuka 120 Limited: Burning Fest. Limited": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ph4.jpg",
  "Arcade Gears: Image Fight and X-Multiply": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9ims.jpg",
  "Battle Garegga": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ozc.jpg",
  "Blast Wind": "https://images.igdb.com/igdb/image/upload/t_cover_big/co61l3.jpg",
  "Cotton 2: Magical Night Dreams": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6iqd.jpg",
  "Capcom Generation 3": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7wtj.jpg",
  "Cotton 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6iqd.jpg",
  "Cotton Boomerang": "https://images.igdb.com/igdb/image/upload/t_cover_big/co99y7.jpg",
  "Darius Gaiden": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2eyg.jpg",
  "Dungeons Dragons Collection": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5b2o.jpg",
  "Darius II": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2eyh.jpg",
  "Detana TwinBee Yahoo! Deluxe Pack": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7m8c.jpg",
  "Dezaemon 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6iqw.jpg",
  "Dodonpachi": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1um4.jpg",
  "Darkstalkers 3": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8pom.jpg",
  "Golden Axe: The Duel": "https://images.igdb.com/igdb/image/upload/t_cover_big/co47yo.jpg",
  "Fantasy Zone": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7zyd.jpg",
  "Gun Frontier": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ev9.jpg",
  "Game Paradise": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7aq6.jpg",
  "Game Tengoku The Game Paradise": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7aq6.jpg",
  "Gekirindan": "https://images.igdb.com/igdb/image/upload/t_cover_big/co483n.jpg",
  "Gradius Deluxe": "https://images.igdb.com/igdb/image/upload/t_cover_big/co695e.jpg",
  "Gradius Deluxe Pack": "https://images.igdb.com/igdb/image/upload/t_cover_big/co695e.jpg",
  "Guardian Force": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3ghg.jpg",
  "Hyper Duel": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7foe.jpg",
  "In the Hunt": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1uc0.jpg",
  "Johnny Bazookatone": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3yql.jpg",
  "Keio Flying Squadron 2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3s8b.jpg",
  "Kingdom Grandprix": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3byj.jpg",
  "Konami Antiques MSX Collection Ultra Pack": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7jk6.jpg",
  "Loaded": "https://images.igdb.com/igdb/image/upload/t_cover_big/co211o.jpg",
  "Layer Section": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ey6.jpg",
  "Layer Section II": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ey6.jpg",
  "Macross Super Dimension Fortress": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4ajj.jpg",
  "Macross: Do You Remember Love?": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4ajj.jpg",
  "Night Warriors: Darkstalkers' Revenge": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8fhf.jpg",
  "Planet Joker": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3mam.jpg",
  "Radiant Silvergun": "https://images.igdb.com/igdb/image/upload/t_cover_big/coa5e6.jpg",
  "Raystorm": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ey6.jpg",
  "Salamander Deluxe Pack Plus": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6y79.jpg",
  "Sengoku Blade": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4lep.jpg",
  "Sexy Parodius": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6vqx.jpg",
  "Shienryu": "https://images.igdb.com/igdb/image/upload/t_cover_big/coa4tr.jpg",
  "Skeleton Warriors": "https://images.igdb.com/igdb/image/upload/t_cover_big/co409y.jpg",
  "Skull Fang": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5mwz.jpg",
  "Sol Divide": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2d66.jpg",
  "Sonic Wings Special": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4sqy.jpg",
  "Soukyugurentai": "https://images.igdb.com/igdb/image/upload/t_cover_big/co61vk.jpg",
  "Soukyugurentai Terra Diver": "https://images.igdb.com/igdb/image/upload/t_cover_big/co61vk.jpg",
  "Space Invaders": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9i9m.jpg",
  "Steam Hearts": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4o69.jpg",
  "Strikers 1945": "https://images.igdb.com/igdb/image/upload/t_cover_big/co23je.jpg",
  "Super Dimension Fortress Macross": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4ajj.jpg",
  "Sengoku Blade: Sengoku Ace Episode II": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4lep.jpg",
  "Sonic Wings": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4sqy.jpg",
  "Steam-Heart's": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4o69.jpg",
  "SEGA Rally Championship": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9ael.jpg",
  "The Legend of Oasis": "https://images.igdb.com/igdb/image/upload/t_cover_big/cobnpp.jpg",
  "Tempest 2000": "https://images.igdb.com/igdb/image/upload/t_cover_big/co72e0.jpg",
  "Terra Cresta 3D": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3j8l.jpg",
  "Thunder Force V": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2e4j.jpg",
  "TwinBee Deluxe Pack": "https://images.igdb.com/igdb/image/upload/t_cover_big/co7m8c.jpg",
  "Waku Waku 7": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3rki.jpg",
  "Axelay": "https://images.igdb.com/igdb/image/upload/t_cover_big/co25my.jpg",
  "Cybernator": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2tnc.jpg",
  "Congo's Caper": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4a0c.jpg",
  "Breath Of Fire II": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9m7u.jpg",
  "Brain Lord": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2oxl.jpg",
  "Daze Before Christmas": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3rqo.jpg",
  "Eek! The Cat": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9v4x.jpg",
  "Firestriker": "https://images.igdb.com/igdb/image/upload/t_cover_big/co3rib.jpg",
  "Gradius III": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9j3p.jpg",
  "Illusion of Gaia": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8kyi.jpg",
  "James Bond Jr": "https://images.igdb.com/igdb/image/upload/t_cover_big/co25rf.jpg",
  "Jurassic Park 2: The Chaos Continues": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2zv4.jpg",
  "Justice League: Task Force": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2wc7.jpg",
  "Live a Live": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5z3l.jpg",
  "Lester the Unlikely": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6ijg.jpg",
  "Maximum Carnage": "https://images.igdb.com/igdb/image/upload/t_cover_big/coal24.jpg",
  "Mighty Morphin Power Rangers: The Fighting Edition": "https://images.igdb.com/igdb/image/upload/t_cover_big/co63o3.jpg",
  "Neugier: Umi to Kaze no Kodō": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4b40.jpg",
  "Porky Pig's Haunted Holiday": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5z4f.jpg",
  "Rendering Ranger: R2": "https://images.igdb.com/igdb/image/upload/t_cover_big/co4a8r.jpg",
  "Secret of Mana": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2u6w.jpg",
  "Secret of Evermore": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8kz6.jpg",
  "Super Smash TV": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5caa.jpg",
  "Super Castlevania": "https://images.igdb.com/igdb/image/upload/t_cover_big/co20dc.jpg",
  "Scooby-Doo Mystery": "https://images.igdb.com/igdb/image/upload/t_cover_big/co38yu.jpg",
  "Super Tennis": "https://images.igdb.com/igdb/image/upload/t_cover_big/co6bjh.jpg",
  "Super Punch-Out!!": "https://images.igdb.com/igdb/image/upload/t_cover_big/co395t.jpg",
  "Terranigma": "https://images.igdb.com/igdb/image/upload/t_cover_big/co26g4.jpg",
  "TIME TRAX": "https://images.igdb.com/igdb/image/upload/t_cover_big/co5zfj.jpg",
  "The Death and Return of Superman": "https://images.igdb.com/igdb/image/upload/t_cover_big/co25nt.jpg",
  "Trials of Mana": "https://images.igdb.com/igdb/image/upload/t_cover_big/co71wc.jpg",
  "The Twisted Tales of Spike McFang": "https://images.igdb.com/igdb/image/upload/t_cover_big/co8lso.jpg",
  "The Flintstones: The Treasure of Sierra Madrock": "https://images.igdb.com/igdb/image/upload/t_cover_big/co2wbg.jpg"
};
